### ISSUE TITLE
User specified constraints

### ISSUE THREAD

**Issue by ssrb19** [jgreener64/ProteinEnsembles.jl#2]
Hello,

I was wondering if the user can specify **CA** constraints. Say I have two proteins and I know that residues x of protein A interacts with residue y of protein B. Is it possible to get perturbations of protein A that satisfy this constraint?

Thanks.

**Comment by jgreener64** [comment]
It's not possible to do this easily. You can alter the interaction matrix manually to change the relevant entry to a bond, e.g. add
```julia
inters[n1,n2] = 1
inters[n2,n1] = 1
```
after line 702 of `src/interactions.jl`, or modified versions after lines 722 and 728 if you are using two conformations. `n1` and `n2` should be the exact indices of the atoms to be constrained. I'm not sure a single constraint will be enough to affect the system significantly though.

**Comment by ssrb19** [comment]
Thanks for the prompt response. I can try doing that. Is there a way of giving more weights to certain interactions? If I could up-weight these few interactions significantly, it might affect the system at large.

**Comment by jgreener64** [comment]
There is not currently a way to up-weight certain interactions - at the moment they are sampled uniformly. Either you could change the sampling (lines 50-54 in `src/generate.jl`) or just add the same constraint multiple times when creating the `Constraint` object, so that it is chosen more often.
