### ISSUE TITLE
Manual input for allosteric restraints

### ISSUE THREAD

**Issue by castephens** [jgreener64/ProteinEnsembles.jl#4]
Hello, 

I'm getting a PROXY error when trying to access the LIGSITESsc link in your READ.md. Is it still available for download?

Alternatively, what is the formatting for the 'pocket_points.pdb'. I'm interested in creating restraints for a manually defined pocket.

thanks!

**Comment by jgreener64** [comment]
Thanks for letting me know. I'll email them to see if it is still available.

Meanwhile there is an example pocket file here: https://github.com/jgreener64/ProteinEnsembles.jl/blob/master/test/test_files/1AKE_pocket_points.pdb

Anything in this format will work. The parser to read this format is here and gives an idea of what the format includes: https://github.com/jgreener64/ProteinEnsembles.jl/blob/master/src/io.jl#L356-L384

**Comment by castephens** [comment]
Great, thank you!

**Comment by castephens** [comment]
If I want to compare a perturbed ensemble with and without a known ligand, would you recommend submitting the modulator file containing the coordinates of the ligand (if I understand correctly those points will have distance constraints generated with protein atoms within 7 Angst?) or a modulator file containing the coordinates of protein atoms I know are forming contacts with the ligand?

**Comment by jgreener64** [comment]
I would use a modulator file with the coordinates of the ligand, modified to look like the pocket file linked above. Label the pocket as 1. Yes, these points will be constrained to protein atoms within 7 Angstrom. You might need to duplicate some of the atoms to see an effect, as LIGSITEcs has a point on each point of a 1 Angstrom grid, which is probably a few more than your modulator. For instance you could copy and paste the same atoms twice or more to give more constraints.

By the way no response from the LIGSITEcs people about the link being down.

**Comment by castephens** [comment]
Great, thanks again. I am getting some interesting results from your method!

Too bad about LIGSITEcs, that must be frustrating.

**Comment by jgreener64** [comment]
Happy to hear it's useful!
